version: 1.0.{build}
image: Visual Studio 2019
configuration: Release
platform: Any CPU
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  version_prefix: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
nuget:
  project_feed: true
before_build:
- cmd: dotnet restore
build:
  publish_nuget: true
  include_nuget_references: true
  verbosity: minimal
deploy:
- provider: NuGet
  api_key:
    secure: hbBd8QpKZSZYpj0l3AAFGJ/9YlaO2B0o9TT6FxkmGr0aNkOJcnMPCKzJFW2w9Yk8
  on:
    branch: main